words = [
  "Biome's",
  "Docker's",
  "PSES",
  "Popen",
  "Prettier's",
  "Tsdk",
  "Wunused",
  "YAXS",
  "agentastic",
  "agnix",
  "aichat",
  "aichat's",
  "alucard",
  "ansible",
  "archiver",
  "astro",
  "autoload",
  "autoloading",
  "bundix",
  "chmod'd",
  "clangd",
  "cli",
  "cmake",
  "commitlint",
  "coreutils",
  "cronometer",
  "cssmodules",
  "deadnix",
  "debugpy",
  "dependabot's",
  "djlsp",
  "dockerfmt",
  "dockerhub",
  "dosgi",
  "esm",
  "fnox",
  "fnox's",
  "gemset",
  "gersemi",
  "getall",
  "ghostty",
  "ghostty's",
  "gitconfig",
  "glab",
  "glab's",
  "godschalk's",
  "golangci",
  "gopls",
  "gunzip",
  "hcl",
  "helmfmt",
  "hexval",
  "homebrew",
  "htmldjango",
  "ifs's",
  "jdtls",
  "jj's",
  "jq's",
  "jqfmt",
  "jsonschema",
  "jvm",
  "langserver",
  "launchd",
  "liga",
  "linters",
  "llm",
  "mapfile",
  "markdownlint",
  "mcp",
  "mermaidfmt",
  "mise",
  "mkdir",
  "mktemp",
  "mvdan",
  "neocmakelsp",
  "nginx",
  "nixd",
  "nixf",
  "nixfmt",
  "nufmt",
  "nushell",
  "objc",
  "oxfmt",
  "oxlint",
  "perltidy",
  "pgfmt",
  "pgrep",
  "pipefail",
  "pkgs",
  "plutil",
  "ppid",
  "proj",
  "pwsh",
  "pylsp",
  "pyobjc",
  "rcs",
  "reflowed",
  "reflows",
  "reformats",
  "retarget",
  "rubocop",
  "rubocop's",
  "sed",
  "shellcheck",
  "shfmt",
  "socio",
  "sourcekit",
  "statix",
  "stdenv",
  "stderr",
  "streamtyped",
  "superhtml",
  "tableplus",
  "taplo",
  "tflint",
  "tokenises",
  "tombi",
  "tsc",
  "tsgo",
  "unarchive",
  "uno",
  "vers",
  "vscode",
  "wght",
  "wsl",
  "xcode's",
  "xcrun",
  "xdg",
  "zdotdir",
  "zeditor",
  "zfs's",
  "zshenv",
]
